### ISSUE TITLE
求助，用来做蒸馏的模型可以是预训练好的下游任务模型么？

### ISSUE THREAD

**Issue by yuansky** [BitVoyage/FastBERT#1]
求助，用来做蒸馏的模型可以是预训练好的下游任务模型么？比如说把基于bert训练的文本分类模型送进去蒸馏~

**Comment by BitVoyage** [comment]
主干网络是复用的bert，所以是能复用的；分类器分支上，论文做了优化，不是简单的全连接，这个和大家各自实现的分类器分支应该是不一致的。

**Comment by yuansky** [comment]
多谢指点，还想咨询您一下，目前的代码只能用在文本分类是么~可以用于实体识别或者机器阅读理解这些任务么

**Comment by BitVoyage** [comment]
目前只能用于分类任务（分支是classifer，且uncertain的判断是基于分类label的分布）

**Comment by 34127chi** [comment]
你好 如果要用预训练好的下游任务模型（分类任务 全连接） 是否只要把代码中的layer_classifier这个模块改成全连接 接着加载下游任务模型得到teacher模型 再直接进行自蒸馏训练分支？

**Comment by BitVoyage** [comment]
可以，只要输出prob的shape一致即可蒸馏学生分类器，不严格要求教师和学生的分类器结构一致
