### ISSUE TITLE
infer脚本模型路径

### ISSUE THREAD

**Issue by puppyapple** [BitVoyage/FastBERT#2]
一个小疑问，script_infer.sh里的--save_model_path是不是应该是saved_model/fastbert_test_distill？

**Comment by BitVoyage** [comment]
目前蒸馏模型的过程，是会在蒸馏过程中覆盖原始模型的。因为蒸馏时，实际上是Freeze原有模型的主干和分类器的参数，然后额外训练11个学生分类器，这样覆盖原有的模型文件，对原有模型的使用（包括再次蒸馏）是没有影响的。

**Comment by puppyapple** [comment]
@BitVoyage 不好意思我今天才匆忙看的代码，不知道是不是我哪里粗心理解错了：
<img width="555" alt="image" src="https://user-images.githubusercontent.com/33118185/82655695-2e3b1a80-9c55-11ea-9325-9061fe10f209.png">
![image](https://user-images.githubusercontent.com/33118185/82655126-4e1e0e80-9c54-11ea-861c-a9bbaf07bc75.png)
训练开始的时候会根据stage是fintune(0)或者是蒸馏(1)来分别把save_model_path_for_train赋值为args.save_model_path(pathA)/args.save_model_path_distill(pathB)，那么pathA存的是对监督数据进行finetune之后的模型，到蒸馏阶段会读取pathA里排序后的最近一个模型，freeze参数进行students分类器的训练，模型都存到了pathB，所以infer的时候按理说应该从pathB读取训练了students的模型？为什么sh脚本里还是读取的pathA里的最新模型呢？

**Comment by BitVoyage** [comment]
不好意思我回答错了， 你一开始指出的问题是对的。代码一开始开发distill的模型是会覆盖原始模型，后来为了不产生歧义，我把两个阶段的模型分开保存了。所以正如你所说，infer的脚本--save_model_path应该在saved_model/fastbert_test_distill。我会修正一下这个bug，感谢

**Comment by puppyapple** [comment]
@puppyapple 感谢分享代码，我在自己数据集上尝试了您和原作者的代码，同时再和huggingface的finetune阶段对比，您的finetune阶段实现的结果和我基于huggingface得到的差距比较小，但原作者的fintune结果就远低于huggingface的。具体差异原因我在研究学习中。

**Comment by BitVoyage** [comment]
我觉得如果结果远低于原始bert的话，应该是某些bug引起的，可能需要看一下代码执行细节哈
