### ISSUE TITLE
batch_size > 1的inference

### ISSUE THREAD

**Issue by puppyapple** [BitVoyage/FastBERT#3]
请问您有尝试过batch size较大的infer实现么？以batch_size为1能从平均时间上看到加速，但如果希望以batch形式进行inference的，尝试了几种实现包括原作者提供的，速度都会变得极慢，因为需要动态地对batch结果进行判断，更新传递给下一层的batch。

**Comment by BitVoyage** [comment]
对的，目前不支持batch size>1。因为模型要根据每1个样本的不同输入，只有真的走到具体第N层，才能决定是否提前返回，故而无法决定在某个batch内如何提前返回（很可能一个batch内提前返回的层数是不同的），就算是batch输入，其实模型如果要实现支持，也是需要挨个判断。如果出现资源利用率上不去的话，建议起多个进程进行预测。还是要看在预测阶段需要大batch的具体痛点是什么。

**Comment by puppyapple** [comment]
嗯嗯是的，多进程是个可以考虑的方向，感谢分享！
